nodeLinker: node-modules
enableGlobalCache: true

npmRegistryServer: "https://registry.npmmirror.com"
unsafeHttpWhitelist:
  - "registry.npmmirror.com"

npmScopes:
  electron:
    npmRegistryServer: "https://registry.npmmirror.com"
  types:
    npmRegistryServer: "https://registry.npmmirror.com"

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - arm64

httpTimeout: 60000 